# Generated by Django 3.2.9 on 2021-11-11 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=30)),
                ('book_publisher', models.CharField(max_length=30)),
                ('book_img', models.ImageField(null=True, upload_to='img')),
                ('book_count', models.BigIntegerField()),
            ],
        ),
    ]
