# Generated by Django 3.2.9 on 2021-11-12 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uno', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('max_num', models.BigIntegerField()),
                ('lend_num', models.BigIntegerField()),
            ],
        ),
    ]
