# Generated by Django 3.2.9 on 2021-11-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lend_num',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='max_num',
            field=models.BigIntegerField(default=10),
        ),
    ]
