# Generated by Django 3.2.9 on 2021-11-12 08:42

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lbookid', models.BigIntegerField()),
                ('lbook', models.CharField(max_length=255)),
                ('ltime', models.DateField(default=django.utils.timezone.now)),
                ('lpublisher', models.CharField(max_length=255)),
                ('uname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.user')),
            ],
        ),
    ]
