# Generated by Django 3.2.9 on 2021-11-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_lend'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='uname',
            field=models.CharField(max_length=255),
        ),
    ]
